name: Test Orca IaC action

on: [pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  iac_scan_job:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - name: Scan IaC
        uses: ./
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: "default"
          path: "test"
          format: "json"
          output: "results/"
          console_output: "cli"
      - uses: actions/upload-artifact@v4.6.0 # ratchet:actions/upload-artifact@v3
        if: always()
        with:
          name: orca-results
          path: results/





